name: test

on:
  push:
    branches: [ master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Action
        id: run_action
        uses: ./
        with:
          mailgun-api-key: ${{ secrets.MAILGUN_API_KEY }}
          mailgun-domain: ${{ secrets.MAILGUN_DOMAIN }}
          mailgun-template: "test-email"
          html-file: "./test.html"
